// cmd/evg-cache/main.go
package main

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/mongodb-labs/migration-tools/cmd/evg-cache/internal/cache"
	"github.com/urfave/cli/v3"
)

// version is set at build time via -ldflags "-X main.version=<value>".
// It defaults to "dev" for local builds.
var version = "dev"

func main() {
	app := &cli.Command{
		Name:  "evg-cache",
		Usage: "Generate Evergreen CI YAML for S3-backed build caching",
		Commands: []*cli.Command{
			generateCmd(),
			versionCmd(),
		},
	}
	if err := app.Run(context.Background(), os.Args); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func generateCmd() *cli.Command {
	return &cli.Command{
		Name:  "generate",
		Usage: "Write Evergreen functions YAML for a cache configuration",
		Flags: []cli.Flag{
			&cli.StringFlag{
				Name:     "name",
				Required: true,
				Usage:    "Cache name (required, matches [a-zA-Z0-9-]+)",
			},
			&cli.StringFlag{
				Name:     "bucket",
				Required: true,
				Usage:    "S3 bucket name",
			},
			&cli.StringFlag{
				Name:     "namespace",
				Required: true,
				Usage:    "S3 namespace / path prefix",
			},
			&cli.StringSliceFlag{
				Name:     "key-file",
				Required: true,
				Usage:    "File to hash for cache key (repeatable)",
			},
			&cli.StringSliceFlag{
				Name:     "cache-path",
				Required: true,
				Usage:    "Path to bundle into tarball (repeatable)",
			},
			&cli.StringSliceFlag{
				Name:  "key-expansion",
				Usage: "Evergreen expansion value to include in the cache key hash (repeatable)",
			},
			&cli.StringFlag{
				Name:  "display-name",
				Usage: "Human-readable name for S3 put (defaults to --name)",
			},
			&cli.StringFlag{
				Name:  "output-file",
				Usage: "Write output to this file instead of stdout",
			},
			&cli.BoolFlag{
				Name:  "omit-setup-function",
				Usage: "Omit the set-up-evg-cache-scripts function from output (useful when multiple caches share one setup function)",
			},
		},
		Action: generate,
	}
}

func versionCmd() *cli.Command {
	return &cli.Command{
		Name:  "version",
		Usage: "Print the evg-cache version",
		Action: func(_ context.Context, _ *cli.Command) error {
			fmt.Println("evg-cache version", version)
			return nil
		},
	}
}

func generate(_ context.Context, cmd *cli.Command) error {
	b, err := cache.NewBuilder(cmd.String("name"))
	if err != nil {
		return err
	}
	displayName := cmd.String("display-name")
	if displayName == "" {
		displayName = cmd.String("name")
	}
	cfg := b.
		WithBucket(cmd.String("bucket")).
		WithNamespace(cmd.String("namespace")).
		WithDisplayName(displayName).
		WithKeyFiles(cmd.StringSlice("key-file")).
		WithKeyExpansions(cmd.StringSlice("key-expansion")).
		WithCachePaths(cmd.StringSlice("cache-path")).
		Build()

	var w io.Writer = os.Stdout
	if outputFile := cmd.String("output-file"); outputFile != "" {
		f, err := os.Create(outputFile)
		if err != nil {
			return fmt.Errorf("creating output file %q: %w", outputFile, err)
		}
		defer f.Close()
		w = f
	}
	return cfg.GenerateFunctions(buildHeader(), cmd.Bool("omit-setup-function"), w)
}

// buildHeader returns the text for the generated-file header comment (without
// the leading "# "), identifying the exact evg-cache command that produced the
// file so users know how to regenerate it.
func buildHeader() string {
	parts := make([]string, 0, len(os.Args))
	parts = append(parts, filepath.Base(os.Args[0]))
	for _, arg := range os.Args[1:] {
		parts = append(parts, shellQuoteArg(arg))
	}
	return fmt.Sprintf(
		"This file was generated by running `%s`. Do not edit this file directly!",
		strings.Join(parts, " "),
	)
}

// shellQuoteArg returns arg quoted for safe inclusion in a POSIX shell command.
// Args that contain only alphanumeric characters and common safe punctuation
// (hyphens, dots, underscores, slashes, colons, at-signs, equals, commas) are
// returned as-is. Everything else is wrapped in single quotes. Embedded single
// quotes are escaped using the standard POSIX idiom (end-quote, escaped
// literal, reopen-quote).
func shellQuoteArg(arg string) string {
	for _, r := range arg {
		if !isSafeShellRune(r) {
			return "'" + strings.ReplaceAll(arg, "'", `'\''`) + "'"
		}
	}
	return arg
}

func isSafeShellRune(r rune) bool {
	return (r >= 'a' && r <= 'z') ||
		(r >= 'A' && r <= 'Z') ||
		(r >= '0' && r <= '9') ||
		strings.ContainsRune("-._/:@=,", r)
}
