// Package generate writes Evergreen functions YAML for evg-cache configurations.
package generate

import (
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/evergreen-ci/shrub"
	"github.com/goccy/go-yaml"
	"github.com/mongodb-labs/migration-tools/cmd/evg-cache/internal/cache"
	"github.com/mongodb-labs/migration-tools/cmd/evg-cache/internal/scripts"
)

// SetupFunctionName is the Evergreen function name for the setup function that
// writes runtime scripts to the agent. It is a constant because the script
// directory is always ./evg-cache-scripts — there is no way to configure a
// different root, so all caches always produce the same setup function name.
// This is intentional: the runtime sentinel makes repeated execution a no-op.
const SetupFunctionName = "set-up-evg-cache-scripts"

// GenerateFunctions writes Evergreen function definitions to w:
//   - restore-<name>-cache: compute key, download artifact, detect hit, extract
//   - save-<name>-cache: create tarball (on miss), upload to S3
//   - set-up-evg-cache-scripts: write runtime scripts to ./evg-cache-scripts on
//     the agent; the runtime sentinel makes repeated execution a no-op.
//     Omitted when omitSetup is true.
//
// header, if non-empty, is written as a YAML comment at the top of the output
// (e.g. "This file was generated by running `evg-cache ...`. Do not edit this
// file directly!"). The leading "# " is added by the YAML encoder.
//
// omitSetup suppresses the set-up-evg-cache-scripts function from the output.
// Use this when multiple cache files are generated and only one of them should
// define the shared setup function.
func GenerateFunctions(
	cfg cache.Config,
	header string,
	omitSetup bool,
	w io.Writer,
) error {
	restoreName := "restore-" + cfg.Name + "-cache"
	saveName := "save-" + cfg.Name + "-cache"

	restoreSeq := shrub.CommandSequence(
		append(cfg.ComputeKeyCommands(), cfg.RestoreCommands()...),
	)
	saveSeq := shrub.CommandSequence(cfg.SaveCommands())

	functions := map[string]*shrub.CommandSequence{
		restoreName: &restoreSeq,
		saveName:    &saveSeq,
	}

	if !omitSetup {
		scriptsFS, err := fs.Sub(scripts.FS, "data")
		if err != nil {
			return fmt.Errorf("accessing embedded scripts: %w", err)
		}
		setupCmds, err := setupScriptsCommands(scriptsFS, cfg.ScriptDir)
		if err != nil {
			return fmt.Errorf("building setup-scripts commands: %w", err)
		}
		setupSeq := shrub.CommandSequence(setupCmds)
		functions[SetupFunctionName] = &setupSeq
	}

	out := struct {
		Functions map[string]*shrub.CommandSequence `yaml:"functions"`
	}{
		Functions: functions,
	}

	encOpts := []yaml.EncodeOption{yaml.UseLiteralStyleIfMultiline(true)}
	if header != "" {
		// The YAML encoder prepends "#" to the comment text; the leading space
		// produces the conventional "# text" spacing.
		encOpts = append(encOpts, yaml.WithComment(yaml.CommentMap{
			"$": []*yaml.Comment{yaml.HeadComment(" " + header)},
		}))
	}
	enc := yaml.NewEncoder(w, encOpts...)
	if err := enc.Encode(out); err != nil {
		return err
	}
	return enc.Close()
}

// scriptEntry holds the data needed to write one embedded script file to the
// Evergreen agent during setup.
type scriptEntry struct {
	Name     string
	DestPath string
	Content  string
	IsShell  bool
}

// setupScriptData is the template data for the generated setup shell script.
type setupScriptData struct {
	Prefix  string
	Scripts []scriptEntry
}

// setupScriptTmpl generates the bash script that writes runtime scripts onto
// the agent. The sentinel file ($SENTINEL_FILE) is touched last so that an
// interrupted run leaves it absent and forces a retry on the next task execution.
var setupScriptTmpl = template.Must(
	template.New("setup").
		Funcs(template.FuncMap{
			"shellquote": func(s string) string { return fmt.Sprintf("%q", s) },
		}).
		Parse(`set -o errexit
set -o nounset
set -o pipefail
if [ -n "${EVG_CACHE_VERBOSE:-}" ]; then set -o verbose; fi

SENTINEL_FILE={{ shellquote .Prefix }}/.setup-complete
if [ -f "$SENTINEL_FILE" ]; then exit 0; fi

mkdir -p {{ shellquote .Prefix }}
{{- range .Scripts }}

# {{ .Name }}
cat > {{ shellquote .DestPath }} << 'EOF'
{{ .Content }}
EOF
{{- if .IsShell }}
chmod +x {{ shellquote .DestPath }}
{{- end }}
{{- end }}

touch "$SENTINEL_FILE"
`),
)

// setupScriptsCommands returns a single shell.exec command that writes all
// files from scriptsFS into scriptDir on the Evergreen agent.
func setupScriptsCommands(
	scriptsFS fs.FS,
	scriptDir string,
) ([]*shrub.CommandDefinition, error) {
	// Use TrimRight to normalize the dir the same way scriptPath() does.
	prefix := strings.TrimRight(scriptDir, "/")

	var entries []scriptEntry
	seen := map[string]string{}
	err := fs.WalkDir(scriptsFS, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		base := filepath.Base(path)
		if prior, ok := seen[base]; ok {
			return fmt.Errorf(
				"scripts %q and %q have the same basename %q; rename one to avoid collision",
				prior,
				path,
				base,
			)
		}
		seen[base] = path
		entry, err := buildScriptEntry(scriptsFS, path, prefix)
		if err != nil {
			return err
		}
		entries = append(entries, entry)
		return nil
	})
	if err != nil {
		return nil, err
	}

	data := setupScriptData{
		Prefix:  prefix,
		Scripts: entries,
	}
	var buf strings.Builder
	if err := setupScriptTmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("executing setup script template: %w", err)
	}

	return []*shrub.CommandDefinition{
		shrub.CmdExecShell{
			Shell:            "bash",
			WorkingDirectory: "${workdir}",
			Script:           buf.String(),
		}.Resolve(),
	}, nil
}

// buildScriptEntry builds a scriptEntry for the file at path in scriptsFS,
// writing the script to prefix/<basename> on the agent.
func buildScriptEntry(scriptsFS fs.FS, path, prefix string) (scriptEntry, error) {
	content, err := fs.ReadFile(scriptsFS, path)
	if err != nil {
		return scriptEntry{}, err
	}

	scriptName := filepath.Base(path)

	// Strip trailing newlines; the template supplies exactly one newline between
	// the content and the EOF delimiter, so the written file ends with a single newline.
	content = bytes.TrimRight(content, "\n")

	return scriptEntry{
		Name:     scriptName,
		DestPath: prefix + "/" + scriptName,
		Content:  string(content),
		IsShell:  strings.HasSuffix(scriptName, ".sh"),
	}, nil
}
