name: Lint

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v3
        with:
          # This matches what we use in the mongosync and mongo-tools repos.
          version: 2026.2.19
      - uses: golangci/golangci-lint-action@v9
        with:
          # mise has already installed the version we want.
          install-mode: "none"
