name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Install tools with `mise`
        uses: jdx/mise-action@v3
        with:
          # This matches what we use in the mongosync and mongo-tools repos.
          version: 2026.2.19
      - name: Run `go test`
        run: go test -v -race ./...
